# Generated by Django 3.1.1 on 2020-09-25 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hierarchy', models.CharField(choices=[('cl', 'Concept_Leader'), ('pl', 'Program_leader'), ('fl', 'FB_leader'), ('dl', 'Direct_leader'), ('ds', 'Desingner')], max_length=2)),
                ('code_number', models.CharField(max_length=10)),
                ('user_web', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(max_length=1000)),
                ('is_filed', models.BooleanField(null=True)),
                ('situation', models.CharField(choices=[('pg', 'Em progresso'), ('fl', 'Finalizado'), ('al', 'Em análise'), ('cl', 'Cancelado')], max_length=2, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concept.programs')),
                ('requested_employ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_employ_id', to='concept.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concept.employees')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concept.task')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_employ_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_employ_id', to='concept.employees')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concept.task')),
            ],
        ),
    ]
